name: Playwright Google SERP

on:
  # ручной запуск из вкладки Actions
  workflow_dispatch:
    inputs:
      query:
        description: 'Запрос для поиска в Google'
        required: false
        default: 'site:example.com'

  # пример расписания (ОТКЛЮЧЕНО, чтобы не жечь минуты)
  # schedule:
  #   - cron: "17 */12 * * *"   # раз в 12 часов, 17-я минута (UTC)

jobs:
  serp:
    runs-on: ubuntu-latest         # Linux → множитель минут ×1
    timeout-minutes: 10            # защита от зависаний
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-playwright.txt
          python -m playwright install --with-deps chromium
          
      - name: Show repo tree (debug)
        run: |
          pwd
          ls -la
          find . -maxdepth 3 -type f | sort
          
      - name: Run scraper
        env:
          QUERY: ${{ github.event.inputs.query }}
        run: |
          python scripts/google_serp_playwright.py

      - name: Upload artifacts (JSON + screenshot)
        uses: actions/upload-artifact@v4
        with:
          name: google-serp-output
          path: out/
