name: Playwright Google SERP

on:
  workflow_dispatch:
    inputs:
      query:
        description: 'Запрос для поиска в Google'
        required: false
        default: 'site:example.com'

jobs:
  serp:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout (force main)
        uses: actions/checkout@v4
        with:
          ref: main           # <-- гарантируем, что берётся ветка main
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-playwright.txt
          python -m playwright install --with-deps chromium

      - name: Show repo tree (debug)
        run: |
          echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
          pwd
          ls -la
          echo "----- find (maxdepth 3) -----"
          find . -maxdepth 3 -type f -print | sort
          echo "----- check file exists -----"
          test -f ./scripts/google_serp_playwright.py && echo "OK: file exists" || (echo "ERROR: file missing" && exit 1)

      - name: Run scraper
        env:
          QUERY: ${{ github.event.inputs.query }}
        run: |
          python ./scripts/google_serp_playwright.py

      - name: Upload artifacts (JSON + screenshot)
        uses: actions/upload-artifact@v4
        with:
          name: google-serp-output
          path: out/
